version: "3.7"

services:
  server: 
    container_name: main-server
    build: 
       context: .
       dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - net

      
networks:
  net: